language: android
android:
    components:
    # use the latest revision of Android SDKTools
    # - platform-tools
    # - tools
    #
    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-L

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-21
    - sys-img-x86-android-23

    licenses:
    - 'android-sdk-license-.+'
